#! /bin/bash
# This script is to be used on the remote VM to send notification to the tilisu server. Copy it to your bin directory on remote VM.

# Sample usage:
# echo "My very high priority message body" | mahiti "Message Title"

### STEP 1
# Obtain the IP address of your PC.
# Following is a possible way to obtain IP of PC. Since I use VNC typically, this is my preferred way
# I am grepping the VNC log file to get the IP of the last connected client
# Alternatively if you have a static IP, you can hard code it to 'ip_addr'

ip_line=`grep "Connections: authenticated" ~/.vnc/SERVER_NAME\:1.log | tail -n 1`
ip_addr=`echo $ip_line | awk '{match($0,"[0-9]+[.][0-9]+[.][0-9]+[.][0-9]+",a)}END{print a[0]}' `
    

### STEP 2
# make a GET request to the server with message title and body
MSG=$(cat | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')
TITLE=$(echo -ne $1 | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g')

curl "$ip_addr:8023/mahiti?title=$TITLE&msg=$MSG"
